version: '3.7'

services:
    web:
        build: .
        command: gunicorn main:app --bind 0.0.0.0:8000 --timeout 120
        expose:
            - 8000
    nginx:
        build: ./nginx
        ports:
            - 80:80
        depends_on :
            - web